---
- name: Install and start application
  hosts: Rhel
  become: true

  tasks:

  - name: Install git
    ansible.builtin.dnf:
      name: git
      state: present

  - name: Clone git repo
    ansible.builtin.git:
      repo: https://github.com/jrswanson4/Summit_Kiosk_Site.git 
      dest: /home/ec2-user/DemoApp
      clone: yes
      update: yes 

  - name: Install node
    ansible.builtin.dnf:
      name: nodejs
      state: present 

  - name: Install npm
    ansible.builtin.command: chdir=/home/ec2-user/DemoApp sudo npm install

  - name: Create service
    ansible.builtin.template:
      src: ../templates/RhelAppDemo.service.j2 
      dest: /lib/systemd/system/RhelAppDemo.service 
  
  - name: Set SElinux permission
    ansible.posix.selinux:
      policy: targeted
      state: permissive
  
  - name: start application
    ansible.builtin.systemd:
      name: RhelAppDemo
      state: started 
    
  - name: check connection
    ansible.builtin.uri:
      url: http://localhost:3000
    until: uri_ouput.status == 200
    retries: 12
    delay: 5  
    register: uri_ouput  

  
    


    

