---
- name: Test using sync for file pull
  hosts: all
  become: true

  tasks:
    - name: sync files
      ansible.posix.synchronize:
        src: /root/HelloWorld
        dest: rsync://3.140.196.57/root/HelloWorld
      delegate_to: 13.58.9.124
        